### ISSUE TITLE
A left-submenu has the wrong offset

### ISSUE THREAD

**Issue by escornwell** [m-thalmann/contextmenujs#1]
When a submenu is moved to the left side of its parent because it is too close to the right edge of the window, it is offset incorrectly. It appears that the left side of the submenu is offset from the left side of the parent menu by the parent menu's width, but it actually needs to be offset by the submenu's width.

When the width of the submenu is less than the width of the parent menu there is a gap between them, which makes the submenu unreachable because the submenu is hidden once the cursor enters the gap.

**Comment by m-thalmann** [comment]
Hey @escornwell! Sorry for my late reply. Can you share a screenshot of the problem?
